import type { FirebaseAdapterOptions } from './types.js'

/**
 * Generates the content of `functions/firebase-params.js`.
 * This file declares Firebase secrets (via defineSecret) and params (via defineString etc.)
 * and is imported by the generated functions/index.js.
 */
export function generateFirebaseParamsModule(
  secrets: string[],
  params: NonNullable<FirebaseAdapterOptions['params']>,
): string {
  const lines: string[] = [
    `// firebase-params.js — GENERATED by adapter-firebase-functions`,
    `// Do not edit manually. Re-run the Next.js build to regenerate.`,
    `'use strict'`,
    ``,
  ]

  const hasSecrets = secrets.length > 0
  const paramEntries = Object.entries(params)
  const hasParams = paramEntries.length > 0

  if (!hasSecrets && !hasParams) {
    lines.push(`// No secrets or params configured.`)
    lines.push(``)
    return lines.join('\n')
  }

  // Build imports
  const imports: string[] = []
  if (hasSecrets) imports.push('defineSecret')
  if (hasParams) {
    const types = new Set(paramEntries.map(([, def]) => def.type))
    if (types.has('string')) imports.push('defineString')
    if (types.has('int')) imports.push('defineInt')
    if (types.has('boolean')) imports.push('defineBoolean')
  }

  lines.push(`const { ${imports.join(', ')} } = require('firebase-functions/params')`)
  lines.push(``)

  if (hasSecrets) {
    lines.push(`// Cloud Secret Manager secrets`)
    for (const name of secrets) {
      lines.push(`exports.${name} = defineSecret(${JSON.stringify(name)})`)
    }
    lines.push(``)
  }

  if (hasParams) {
    lines.push(`// Environment configuration params`)
    for (const [name, def] of paramEntries) {
      const opts: Record<string, unknown> = {}
      if (def.default !== undefined) opts.default = def.default
      if (def.description) opts.description = def.description
      const fn =
        def.type === 'string' ? 'defineString' : def.type === 'int' ? 'defineInt' : 'defineBoolean'
      const optsStr = Object.keys(opts).length > 0 ? `, ${JSON.stringify(opts)}` : ''
      lines.push(`exports.${name} = ${fn}(${JSON.stringify(name)}${optsStr})`)
    }
    lines.push(``)
  }

  return lines.join('\n')
}
