import type { FirebaseAdapterOptions, ResolvedCacheTagsOptions } from './types.js'

/** Next.js internal constant — the header cache tags are stored under in cache entry metadata. */
const NEXT_CACHE_TAGS_HEADER = 'x-next-cache-tags'
/** Next.js internal constant — prefix for implicit, path-derived tags. */
const NEXT_CACHE_IMPLICIT_TAG_PREFIX = '_N_T_'

export interface FunctionsEntryOptions {
  functionName: string
  secrets: string[]
  params: NonNullable<FirebaseAdapterOptions['params']>
  /** Null disables cache-tag exposure entirely — no runtime code is emitted for it. */
  cacheTags?: ResolvedCacheTagsOptions | null
}

/**
 * Generates the content of `functions/index.js` — the Firebase Functions entry point.
 */
export function generateFunctionsEntry({
  functionName,
  secrets,
  params,
  cacheTags = null,
}: FunctionsEntryOptions): string {
  const allBindings = [...secrets, ...Object.keys(params)]

  // Secret names are interpolated as identifiers — validated upstream with [A-Z0-9_]+
  const secretsArrayCode = secrets.length > 0 ? `[${secrets.join(', ')}]` : `[]`

  const destructure =
    allBindings.length > 0
      ? `const { ${allBindings.join(', ')} } = require('./firebase-params')\n`
      : ''

  // Emitted only when cache tags are enabled — keeps the generated file lean otherwise.
  const cacheTagsRuntime = cacheTags
    ? `const _cacheTags = ${JSON.stringify(cacheTags)}
const _NEXT_CACHE_TAGS_HEADER = ${JSON.stringify(NEXT_CACHE_TAGS_HEADER)}
const _IMPLICIT_TAG_PREFIX = ${JSON.stringify(NEXT_CACHE_IMPLICIT_TAG_PREFIX)}

// Next.js strips the cache-tags header from responses unless it is running in
// "minimal mode" (the Vercel contract, where the platform owns routing). We read
// the tags off the response cache entry instead, via the requestMeta.onCacheEntry
// hook, and set the CDN header ourselves before Next.js writes the response.
// Applies to App Router pages only — Route Handlers expose no equivalent hook.
function _joinTags(raw) {
  let tags = String(raw).split(',').map(t => t.trim()).filter(Boolean)
  if (_cacheTags.stripImplicitTags) {
    tags = tags.filter(t => !t.startsWith(_IMPLICIT_TAG_PREFIX))
  }
  let value = ''
  for (const tag of tags) {
    const next = value ? value + ',' + tag : tag
    // Truncate on a tag boundary — a half-written tag would purge nothing.
    if (Buffer.byteLength(next, 'utf8') > _cacheTags.maxBytes) break
    value = next
  }
  return value
}

function _makeCacheTagMeta(res) {
  return {
    onCacheEntry(cacheEntry) {
      try {
        const headers = cacheEntry && cacheEntry.value && cacheEntry.value.headers
        const raw = headers && headers[_NEXT_CACHE_TAGS_HEADER]
        if (typeof raw === 'string' && raw.length > 0 && !res.headersSent) {
          const value = _joinTags(raw)
          if (value) {
            res.setHeader(_cacheTags.header, value)
            if (_cacheTags.includeNextHeader) res.setHeader(_NEXT_CACHE_TAGS_HEADER, value)
          }
        }
      } catch (err) {
        console.error('[adapter-firebase-functions] cache tag header failed:', err)
      }
      // false = we did not respond; let Next.js continue its normal response flow.
      return false
    },
  }
}

`
    : ''

  // The init hook is likewise conditional — `_cacheTags` does not exist when disabled.
  const cacheTagsInit = cacheTags
    ? `
        if (typeof app.getRequestHandlerWithMetadata === 'function') {
          _handlerWithMeta = meta => app.getRequestHandlerWithMetadata(meta)
        } else {
          console.warn(
            '[adapter-firebase-functions] cacheTags enabled but this Next.js version has no ' +
              'getRequestHandlerWithMetadata() — cache tag headers will not be emitted.',
          )
        }`
    : ''

  // With cache tags on, the handler is rebuilt per request so the onCacheEntry
  // closure can capture `res` — the same wiring Next.js's own render-server uses.
  const handlerCall = cacheTags
    ? '(_handlerWithMeta ? _handlerWithMeta(_makeCacheTagMeta(res)) : _handler)'
    : '_handler'

  return `// index.js — GENERATED by adapter-firebase-functions
// Do not edit manually. Re-run the Next.js build to regenerate.
'use strict'

const { onRequest } = require('firebase-functions/v2/https')
${destructure}
const _manifest = (() => {
  try { return require('./deployment-manifest.json') } catch { return {} }
})()

const _functionOpts = {
  // Defaults (overridden by manifest config)
  timeoutSeconds: 60,
  memory: '1GiB',
  minInstances: 0,
  concurrency: 80,
  invoker: 'public',
  // Spread full config from manifest
  ...(_manifest.function?.config ?? {}),
  // Secrets always override (they're bound SecretParam references, not config)
  secrets: ${secretsArrayCode},
}

// Stub 'inspector' module if it is not available (Firebase Functions emulator
// runs in a pkg-bundled process that strips the V8 Inspector). Next.js requires
// the module at startup to detect whether a debugger is attached — a no-op stub
// is sufficient for production use.
;(function patchInspector() {
  try { require('inspector') } catch (e) {
    if (e && e.code === 'ERR_INSPECTOR_NOT_AVAILABLE') {
      const Module = require('module')
      const _orig = Module._load.bind(Module)
      Module._load = function (id, parent, isMain) {
        if (id === 'inspector' || id === 'node:inspector') {
          return { url: () => null, open: () => {}, close: () => {}, waitForDebugger: () => {} }
        }
        return _orig(id, parent, isMain)
      }
    }
  }
}())

${cacheTagsRuntime}let _handler = null
${cacheTags ? 'let _handlerWithMeta = null\n' : ''}let _initErr = null
let _initPromise = null

// Deferred init: lazily started on first request rather than module load.
// This avoids ERR_INSPECTOR_NOT_AVAILABLE when the emulator loads the module
// in its pkg-bundled Node context during function discovery.
function _startInit() {
  if (!_initPromise) {
    _initErr = null
    _initPromise = (async () => {
      try {
        let conf = {}
        try { conf = require('./runtime-next-config.json') } catch { /* use empty config */ }
        const next = require('next')
        const app = next({ dev: false, dir: __dirname, conf })
        await app.prepare()
        _handler = app.getRequestHandler()${cacheTagsInit}
      } catch (err) {
        _initErr = err
        _initPromise = null  // allow retry on next request
        console.error('[adapter-firebase-functions] init failed:', err)
      }
    })()
  }
  return _initPromise
}

exports[${JSON.stringify(functionName)}] = onRequest(_functionOpts, async (req, res) => {
  await _startInit()
  if (_initErr || !_handler) {
    if (!res.headersSent) res.status(500).send('Internal Server Error')
    return
  }
  // Cloud Functions always pre-reads the entire request body into req.rawBody (Buffer)
  // before calling this handler — including multipart/form-data and text/plain Server Actions.
  // The underlying IncomingMessage stream is left in a consumed/ended state. Next.js converts
  // the Node stream to a Web ReadableStream via Readable.toWeb() / fromNodeNextRequest(), which
  // hangs if the stream is destroyed or ended with no data.
  // Fix: swap in a fresh _readableState and use a pull-based _read that pushes rawBody on demand,
  // so Next.js can read the body regardless of what state Firebase left the stream in.
  if (Buffer.isBuffer(req.rawBody)) {
    const { Readable } = require('stream')
    const _raw = req.rawBody
    const _fresh = new Readable({ read() {} })
    req._readableState = _fresh._readableState
    req._read = function () {
      this.push(_raw)
      this.push(null)
      this._read = function () {}
    }
  }
  try {
    await ${handlerCall}(req, res)
  } catch (err) {
    console.error('[adapter-firebase-functions] request error:', err)
    if (!res.headersSent) res.status(500).send('Internal Server Error')
  }
})
`
}
