import type { FirebaseAdapterOptions } from './types.js'

/**
 * Generates the content of `functions/index.js` — the Firebase Functions entry point.
 */
export function generateFunctionsEntry(
  functionName: string,
  secrets: string[],
  params: NonNullable<FirebaseAdapterOptions['params']>,
): string {
  const allBindings = [...secrets, ...Object.keys(params)]

  // Secret names are interpolated as identifiers — validated upstream with [A-Z0-9_]+
  const secretsArrayCode = secrets.length > 0 ? `[${secrets.join(', ')}]` : `[]`

  const destructure =
    allBindings.length > 0
      ? `const { ${allBindings.join(', ')} } = require('./firebase-params')\n`
      : ''

  return `// index.js — GENERATED by adapter-firebase-functions
// Do not edit manually. Re-run the Next.js build to regenerate.
'use strict'

const { onRequest } = require('firebase-functions/v2/https')
${destructure}
const _manifest = (() => {
  try { return require('./deployment-manifest.json') } catch { return {} }
})()

const _functionOpts = {
  // Defaults (overridden by manifest config)
  timeoutSeconds: 60,
  memory: '1GiB',
  minInstances: 0,
  concurrency: 80,
  invoker: 'public',
  // Spread full config from manifest
  ...(_manifest.function?.config ?? {}),
  // Secrets always override (they're bound SecretParam references, not config)
  secrets: ${secretsArrayCode},
}

// Stub 'inspector' module if it is not available (Firebase Functions emulator
// runs in a pkg-bundled process that strips the V8 Inspector). Next.js requires
// the module at startup to detect whether a debugger is attached — a no-op stub
// is sufficient for production use.
;(function patchInspector() {
  try { require('inspector') } catch (e) {
    if (e && e.code === 'ERR_INSPECTOR_NOT_AVAILABLE') {
      const Module = require('module')
      const _orig = Module._load.bind(Module)
      Module._load = function (id, parent, isMain) {
        if (id === 'inspector' || id === 'node:inspector') {
          return { url: () => null, open: () => {}, close: () => {}, waitForDebugger: () => {} }
        }
        return _orig(id, parent, isMain)
      }
    }
  }
}())

let _handler = null
let _initErr = null
let _initPromise = null

// Deferred init: lazily started on first request rather than module load.
// This avoids ERR_INSPECTOR_NOT_AVAILABLE when the emulator loads the module
// in its pkg-bundled Node context during function discovery.
function _startInit() {
  if (!_initPromise) {
    _initErr = null
    _initPromise = (async () => {
      try {
        let conf = {}
        try { conf = require('./runtime-next-config.json') } catch { /* use empty config */ }
        const next = require('next')
        const app = next({ dev: false, dir: __dirname, conf })
        await app.prepare()
        _handler = app.getRequestHandler()
      } catch (err) {
        _initErr = err
        _initPromise = null  // allow retry on next request
        console.error('[adapter-firebase-functions] init failed:', err)
      }
    })()
  }
  return _initPromise
}

exports[${JSON.stringify(functionName)}] = onRequest(_functionOpts, async (req, res) => {
  await _startInit()
  if (_initErr || !_handler) {
    if (!res.headersSent) res.status(500).send('Internal Server Error')
    return
  }
  // Cloud Functions always pre-reads the entire request body into req.rawBody (Buffer)
  // before calling this handler — including multipart/form-data and text/plain Server Actions.
  // The underlying IncomingMessage stream is left in a consumed/ended state. Next.js converts
  // the Node stream to a Web ReadableStream via Readable.toWeb() / fromNodeNextRequest(), which
  // hangs if the stream is destroyed or ended with no data.
  // Fix: swap in a fresh _readableState and use a pull-based _read that pushes rawBody on demand,
  // so Next.js can read the body regardless of what state Firebase left the stream in.
  if (Buffer.isBuffer(req.rawBody)) {
    const { Readable } = require('stream')
    const _raw = req.rawBody
    const _fresh = new Readable({ read() {} })
    req._readableState = _fresh._readableState
    req._read = function () {
      this.push(_raw)
      this.push(null)
      this._read = function () {}
    }
  }
  try {
    await _handler(req, res)
  } catch (err) {
    console.error('[adapter-firebase-functions] request error:', err)
    if (!res.headersSent) res.status(500).send('Internal Server Error')
  }
})
`
}
