import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { generateFirebaseParamsModule } from '../../src/firebase-params.js'

describe('generateFirebaseParamsModule', () => {
  it('returns empty module when no secrets or params', () => {
    const output = generateFirebaseParamsModule([], {})
    assert.ok(output.includes('No secrets or params configured'))
    assert.ok(!output.includes('defineSecret'))
    assert.ok(!output.includes('defineString'))
  })

  it('generates defineSecret imports and exports for secrets only', () => {
    const output = generateFirebaseParamsModule(['DATABASE_URL', 'STRIPE_KEY'], {})
    assert.ok(output.includes("const { defineSecret } = require('firebase-functions/params')"))
    assert.ok(output.includes("exports.DATABASE_URL = defineSecret(\"DATABASE_URL\")"))
    assert.ok(output.includes("exports.STRIPE_KEY = defineSecret(\"STRIPE_KEY\")"))
    assert.ok(!output.includes('defineString'))
    assert.ok(!output.includes('defineInt'))
    assert.ok(!output.includes('defineBoolean'))
  })

  it('generates correct define* calls for params only', () => {
    const output = generateFirebaseParamsModule([], {
      API_URL: { type: 'string', default: 'https://api.example.com' },
      MAX_RETRIES: { type: 'int', default: 3 },
      ENABLE_LOGS: { type: 'boolean', default: true },
    })
    assert.ok(!output.includes('defineSecret'))
    assert.ok(output.includes('defineString'))
    assert.ok(output.includes('defineInt'))
    assert.ok(output.includes('defineBoolean'))
    assert.ok(output.includes('exports.API_URL = defineString("API_URL"'))
    assert.ok(output.includes('"default":"https://api.example.com"'))
    assert.ok(output.includes('exports.MAX_RETRIES = defineInt("MAX_RETRIES"'))
    assert.ok(output.includes('"default":3'))
    assert.ok(output.includes('exports.ENABLE_LOGS = defineBoolean("ENABLE_LOGS"'))
    assert.ok(output.includes('"default":true'))
  })

  it('generates both sections for mixed secrets and params', () => {
    const output = generateFirebaseParamsModule(['MY_SECRET'], {
      REGION: { type: 'string', default: 'us-central1' },
    })
    assert.ok(output.includes('defineSecret'))
    assert.ok(output.includes('defineString'))
    assert.ok(output.includes("exports.MY_SECRET = defineSecret(\"MY_SECRET\")"))
    assert.ok(output.includes('exports.REGION = defineString("REGION"'))
    // Import line should have both
    assert.ok(output.includes('defineSecret, defineString'))
  })

  it('deduplicates secrets', () => {
    // Deduplication happens in adapter.ts before calling this function,
    // but if passed duplicates, each generates a line
    const output = generateFirebaseParamsModule(['DUP', 'DUP'], {})
    const matches = output.match(/exports\.DUP = defineSecret/g)
    // The function itself does not deduplicate — adapter.ts does via new Set()
    assert.ok(matches !== null && matches.length === 2)
  })

  it('includes description in param options when provided', () => {
    const output = generateFirebaseParamsModule([], {
      MY_PARAM: { type: 'string', description: 'A helpful description' },
    })
    assert.ok(output.includes('"description":"A helpful description"'))
  })

  it('omits options object when param has no default or description', () => {
    const output = generateFirebaseParamsModule([], {
      BARE_PARAM: { type: 'string' },
    })
    assert.ok(output.includes('exports.BARE_PARAM = defineString("BARE_PARAM")'))
    // No trailing comma + JSON options
    assert.ok(!output.includes('exports.BARE_PARAM = defineString("BARE_PARAM",'))
  })

  it('only imports the define* functions actually needed', () => {
    const output = generateFirebaseParamsModule([], {
      ONLY_INT: { type: 'int' },
    })
    assert.ok(output.includes('defineInt'))
    assert.ok(!output.includes('defineString'))
    assert.ok(!output.includes('defineBoolean'))
    assert.ok(!output.includes('defineSecret'))
  })

  it('always includes use strict and header comment', () => {
    const output = generateFirebaseParamsModule([], {})
    assert.ok(output.includes("'use strict'"))
    assert.ok(output.includes('GENERATED by adapter-firebase-functions'))
  })
})
