import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { generateFunctionsEntry } from '../../src/runtime-template.js'

describe('generateFunctionsEntry', () => {
  it('generates empty secrets array when no secrets', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('secrets: []'))
    // No destructure line from firebase-params
    assert.ok(!output.includes("require('./firebase-params')"))
  })

  it('generates correct destructure and secrets array with secrets', () => {
    const output = generateFunctionsEntry('nextjs', ['DB_URL', 'API_KEY'], {})
    assert.ok(output.includes("const { DB_URL, API_KEY } = require('./firebase-params')"))
    assert.ok(output.includes('secrets: [DB_URL, API_KEY]'))
  })

  it('includes params in destructure but NOT in secrets array', () => {
    const output = generateFunctionsEntry('nextjs', [], {
      MY_PARAM: { type: 'string' },
    })
    assert.ok(output.includes("const { MY_PARAM } = require('./firebase-params')"))
    assert.ok(output.includes('secrets: []'))
  })

  it('handles mixed secrets and params correctly', () => {
    const output = generateFunctionsEntry('nextjs', ['SECRET_A'], {
      PARAM_B: { type: 'int' },
    })
    assert.ok(output.includes("const { SECRET_A, PARAM_B } = require('./firebase-params')"))
    // Only secrets in the secrets array, not params
    assert.ok(output.includes('secrets: [SECRET_A]'))
    assert.ok(!output.includes('secrets: [SECRET_A, PARAM_B]'))
  })

  it('uses __dirname for next() dir option', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('dir: __dirname'))
  })

  it('function name is baked in at build time as a static export key', () => {
    const output = generateFunctionsEntry('myFunction', [], {})
    assert.ok(output.includes('exports["myFunction"]'))
    // Should NOT use dynamic runtime manifest lookup for the name
    assert.ok(!output.includes("_manifest.function?.name ?? 'nextjs'"))
    assert.ok(!output.includes('exports[_functionName]'))
  })

  it('uses default function name nextjs', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('exports["nextjs"]'))
  })

  it('includes init error handling with retry on failure', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('_initErr'))
    assert.ok(output.includes('[adapter-firebase-functions] init failed:'))
    assert.ok(output.includes('status(500)'))
    // _initPromise reset to null on failure allows retry
    assert.ok(output.includes('_initPromise = null'))
  })

  it('spreads manifest config into function opts', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('...(_manifest.function?.config ?? {})'))
  })

  it('includes default values for function options', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('timeoutSeconds: 60'))
    assert.ok(output.includes("memory: '1GiB'"))
    assert.ok(output.includes('minInstances: 0'))
    assert.ok(output.includes('concurrency: 80'))
    assert.ok(output.includes("invoker: 'public'"))
  })

  it('always includes use strict and header comment', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes("'use strict'"))
    assert.ok(output.includes('GENERATED by adapter-firebase-functions'))
  })

  it('includes rawBody stream restoration for Cloud Functions body pre-reading', () => {
    const output = generateFunctionsEntry('nextjs', [], {})
    assert.ok(output.includes('req.rawBody'))
    assert.ok(output.includes('_readableState'))
  })
})
